name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    name: Run on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Build
        run: |
          pnpm i --frozen-lockfile
          pnpm run build  
          pnpm run doc  
          pnpm run bundle  

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: pnpm run lint --scope "@feld-ai/*" 

      - name: Test
        if: matrix.os == 'macos-latest'
        run: |
          set NODE_OPTIONS=--max_old_space_size=4096
          pnpm run test --scope "@feld-ai/*" 
